name: Build Web Application

on:
  push:
    branches:
      - main

jobs:
  # Build Stage
  build:
    name: Build the web application
    runs-on: ubuntu-20.04

    env:
      BUILD_CONFIGURATION: Release
      WWWROOT_DIR: Tailspin.SpaceGame.Web/wwwroot
      DOTNET_SDK_VERSION: 6.0.x

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Use the specified .NET SDK version
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      # Install NPM dependencies
      - name: Install NPM Packages
        run: npm install

      # Compile Sass assets
      - name: Compile Sass Assets
        run: ./node_modules/.bin/node-sass ${{ env.WWWROOT_DIR }} --output ${{ env.WWWROOT_DIR }}

      # Run Gulp tasks
      - name: Run Gulp Tasks
        run: npx gulp

      # Write build info
      - name: Write Build Info
        run: echo "$(GITHUB_REPOSITORY), ${{ github.run_id }}, ${{ github.run_number }}" > buildinfo.txt
        working-directory: ${{ env.WWWROOT_DIR }}

      # Restore .NET dependencies
      - name: Restore .NET Dependencies
        run: dotnet restore

      # Build the project
      - name: Build the Project
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

      # Publish the project
      - name: Publish the Project
        run: dotnet publish --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --output ./publish

      # Upload the artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: drop
          path: ./publish


  # Deploy Stage
  deploy:
    name: Deploy the Web Application
    runs-on: ubuntu-20.04
    needs: build # This ensures the Deploy job only runs if Build succeeds

    steps:
      # Download the artifact from the build job
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: drop
      
      # check download artifact
      - name: List Downloaded Artifact Contents
        run: |
          ls -l 

      # Login to Azure using service principal
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.WEBAPP_NAME }}
          slot-name: production
          package: ./publish

      # Deploy Function App
      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.FUNCTIONAPP_NAME }}
          package: ./publish